import Head from 'next/head'
import Banner from '../components/About/Banner'
import Hero from '../components/About/Hero'
import Header from '../components/Header'

const about = () => {
  return (
    <div>
        <Head>
            <title>Arch Studio | Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <Hero />
        <Banner />
    </div>
  )
}

export default about