import React from 'react'
import Head from 'next/head'
import Header from '../components/Header'
import Footer from '../components/Footer'
import Hero from '../components/Contact/Hero'
import CDetails from '../components/Contact/CDetails'
import Map from '../components/Contact/Map'

const contact = () => {
  return (
    <div>
        <Head>
            <title>Arch Studio | Contact</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <Hero />
        <CDetails />
        {/* <Map /> */}
        <Footer />
        
    </div>
  )
}

export default contact