import Header from '../components/Header'
import Footer from '../components/Footer'
import Head from 'next/head'
import Portfolio from '../components/Portfolio/Portfolio'

const portfolio = () => {
  return (
    <div>
        <Head>
            <title>Arch Studio | Portfolio</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>

        <Header />
        <div className='relative w-full'>
            <Portfolio />
                <div className='hidden md:inline-block absolute rotate-90 tracking-[0.5em] font-semibold text-lg text-gray-400 top-24 left-0 uppercase'>
                    Portfolio
                </div>
        </div>
        <Footer />
    </div>
  )
}

export default portfolio